### ISSUE TITLE
Browserify compatibilty error

### ISSUE THREAD

**Issue by marianobrc** [jaruba/node-vlcPlayer-demo#4]
Hi, i'm try it to use wcjs-player on the browser with browserify, is it possible?

I'm getting this error:

browserify main.js -o bundle.js

Error: Cannot find module 'remote' from '/home/diremar/webtorrentplayer/webstorm-bootstrap/node_modules/wcjs-player'
    at /usr/lib/node_modules/browserify/node_modules/resolve/lib/async.js:46:17
    at process (/usr/lib/node_modules/browserify/node_modules/resolve/lib/async.js:173:43)
    at ondir (/usr/lib/node_modules/browserify/node_modules/resolve/lib/async.js:188:17)
    at load (/usr/lib/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
    at onex (/usr/lib/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
    at /usr/lib/node_modules/browserify/node_modules/resolve/lib/async.js:22:47
    at Object.oncomplete (fs.js:108:15)

**Comment by RSATom** [comment]
don't sure it's possible use binary .node modules in regular browsers.

**Comment by marianobrc** [comment]
I've used WebTorrent modules on the browser with browserify, but it's pure javascript.

**Comment by RSATom** [comment]
`WebChimera.js` is binary module - so it can't be used in regular browsers. You could use `WebChimera Plugin` but its support will be dropped at Chrome at September (after full NPAPI removing).

**Comment by marianobrc** [comment]
Ok, thanks for your answer.
Regards
